### ISSUE TITLE
AngularJS error

### ISSUE THREAD

**Issue by PeziBuu** [piwik/plugin-LoginLdap#110]
Hello community,

i got a proble with the LDAP plugin. We are using the current version of Piwik (2.14). After I activate the Plugin and move to the new option button, I only see the headlines but missing all the option section. The browser console gves me an angularJS error:

Error: [ng:areq] http://errors.angularjs.org/1.2.28/ng/areq?p0=LoginLdapAdminController&p1=not%20a%20function%2C%20got%20undefined

Does anybody can help me with this issue? If you need more information, let me know.

Thanks, Peter

**Comment by diosmosis** [comment]
I think the JavaScript the browser uses is incorrect or it is not being regenerated correctly by Piwik. Please try clearing the browser cache and/or running the `core:clear-caches` command (via `./console core:clear-caches`).

**Comment by PeziBuu** [comment]
with the new version of Piwik, the Plugin works, but when i insert the search filter and try to test it, i get the following error:
{"result":"error","message":"Call to undefined function Piwik\\Plugins\\LoginLdap\\Ldap\\ldap_connect()"}
Could there be an error in my filter?

**Comment by diosmosis** [comment]
This is a server configuration issue. Your PHP cannot find the ldap_connect method for some reason. Your LDAP extension may not be loaded for whatever PHP environment is handling web requests (ie, php-cgi or php-fpm or apache's mod_php).

This guide may help in troubleshooting your server config: https://github.com/piwik/plugin-LoginLdap/wiki/Troubleshooting
