### ISSUE TITLE
NO configuration section

### ISSUE THREAD

**Issue by amgabbert** [piwik/plugin-LoginLdap#116]
I tried to add a new ldap server today in piwik and my ldap connection broke.  When I restored my config.php.ini file, I am still getting an error that I cannot figure out:

LDAP server info 'US.LMCO.COM' is configured incorrectly: No configuration section [US.LMCO.COM] found.    Can anyone tell me what it is looking for and where?

**Comment by diosmosis** [comment]
It's looking in your `/path/to/piwik/config/config.ini.php` file. It should be looking for `[LoginLdap_US.LMCO.COM]` though.

What do you mean your "ldap connection broke"? And why did you need to restore your config.ini.php file? Did it disappear?

**Comment by amgabbert** [comment]
Thank you!  That corrected it ☺

Allison Gabbert

**Comment by diosmosis** [comment]
Glad it's working, closing this issue.
