### ISSUE TITLE
Disable possibility to change personal settings for users from LDAP

### ISSUE THREAD

**Issue by adaqus** [piwik/plugin-LoginLdap#126]
We assume that all users that are synchronized from LDAP should not be able to change password, alias, e-mail in Personal settings. Why? If user from LDAP changes password, he becames a normal Piwik user and is not synchronized with LDAP server any more. This is not desired behavior if we assume that users want to keep users management on LDAP side.

**Comment by mattab** [comment]
Fixed in https://github.com/piwik/plugin-LoginLdap/pull/128
