### ISSUE TITLE
Checking for a plugin configuration issue

### ISSUE THREAD

**Issue by plegault3397** [piwik/plugin-LoginLdap#133]
I'm using php54 on RedHat 
I get an error using this
php ./console loginldap:synchronize-users --login=<login> -vvv

PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/rh/php54/root/usr/lib64/php/modules/pdo_mysql.so' - /opt/rh/php54/root/usr/lib64/php/modules/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0

**Comment by mattab** [comment]
Hi @plegault3397 

Check your php configuration in `php.ini` file, also search on the internet for other tips, cheers
