### ISSUE TITLE
LoginLdap automatically uninstalls after a short period of time

### ISSUE THREAD

**Issue by duspal** [piwik/plugin-LoginLdap#139]
As title says, the module is uninstalling after a short period of time (about 15-30 minutes).  I traced the issue back to the config file -- the lines that contains Plugins[] = "LoginLdap" disappears after a few minutes.  I don't know whats causing this to happen.

Further, if you remove Plugins[] = "Login" and PluginsInstalled[] = "Login" from the config file, they will both reappear at the same time that Plugins[] = "LoginLdap" disappears from the config file.

My current workaround is to change ownership of the config.ini.php from apache to root, to prevent auto updating of this file.  This is fine for now, but it causes us to hand-add changes to the config, which can only be done by a SysAdmin.

**Comment by nwoetzel** [comment]
Is this only happening for the Plugins and PluginsInstalled section, or are you also loosing other configurations in the config.ini.php file (like the configured Ldap servers).
When you activate/deactivate other Plugins, are they also deactivated/reactivated in that described process.

**Comment by duspal** [comment]
Its only happening for Plugins and PluginsInstalled.

I have a few other plugins activated (Tree Visualization comes to mind, but there are one or two others) and these activate and deactive as I would expect, and don't get auto-deactivated when the LDAP plugin does.

(i.e. this issue seems to be limited to LDAP as far as I can tell)

**Comment by nwoetzel** [comment]
Since we want to use this plugin in production, I am interested in understanding your particular problem.
Some key questions are of interest in your error Report:
What are the versions of your deployment:
piwik
LoginLdap plugin

The current LoginLdap in version 3.3.1 requires piwik 2.16.0
I assume that when it is installed it is working as expected?

Does the LoginLdap disappear from both ini sections: Plugins and PluginsInstalled?

**Comment by duspal** [comment]
We're currently on Piwik version 2.16.1.  LoginLdap is on version 3.3.0 according to the CHANGELOG.md file.

Beside the issues listed above, when LoginLdap is installed its working as expected (no other quirks noted or workarounds needed). 

And yes, LoginLdap does disappear from both ini sections.

**Comment by nwoetzel** [comment]
This is really strange. I cannot see the meaning of such functionality.
I guess you have enabled logging and you cannot see anything in the logs that would stand out in respect to automatic installation/uninstallation of plugins.
I am currently developing and working on piwik master branch. When I am finished with my current work on the plugin, I will try to test the combination 2.16.1 piwik with 3.3.0 LoginLdap.
Even if I cannot resolve the issue, the information will help others. Thanks for the report.

**Comment by duspal** [comment]
I did comb through the error logs at the time the issue was occurring and didn't see anything at the time that would trigger me to investigate it.

I'll check it again the next time we do scheduled maintenance. Will let you know if I ever find anything, though I wouldn't be surprised if there wasn't an error log since it was just overwriting a file, which may not show as an error.

I'll also report after our next upgrade if the issue resolved, though it may be awhile before then.

**Comment by mattab** [comment]
Could not reproduce

**Comment by josmitc** [comment]
I see this particular issue in our Docker swarm, where we're running Piwik in development. Anytime we push an update, the LDAP plugin is disabled and I have to reinstall it. However, right after the reinstall, it picks up the settings directly from the config.ini.php file.
