### ISSUE TITLE
Issue with piwik 3.0.0-rc1 password hash change

### ISSUE THREAD

**Issue by kachenjr** [piwik/plugin-LoginLdap#148]
Hope I'm not missing that this is addressed somewhere else, but there seems to be a major change in this pull
[https://github.com/piwik/piwik/pull/10926](https://github.com/piwik/piwik/pull/10926)
that breaks some of the logic in LoginLdap.  Namely, the passwords stored by UsersManager are now hashed with an extra function call before they are stored.   The LoginLdap plugin assumes it is getting the hashed password it sent to the user manager back out of the database, but this is no longer the case.
See plugins/UsersManager/API.php at line 455 for the extra hash call.
Everything was working fine until we pulled the rc1 tag, and now this plugin is not compatible.  I don't see and issue listed for this yet, so I'm hoping to make sure you're aware of this.

Thanks!

**Comment by sgiehl** [comment]
LoginLdap is not yet compatible with Piwik 3. We try to release a compatible version till final Piwik 3 release

**Comment by kachenjr** [comment]
Update, incase you haven't gotten into it yet, there are two breaking issues.

1. isLdapUser no longer works due to the extra hash of the password value before storing in the database.
2. userManagerApi->getTokenAuth will no longer work because we do not have a way to regenerate the original md5 hashed version of the password that was stored in the database.  This was fetched from the userModelAPI->getUser method before as the password field.

I've been able to get things working locally by:
1.  hardcoding the UserMapper->isLdapUser call to return true.  I'm not aware of the use case where the list of ldap and non-ldap users would overlap, so I can't add anymore help to this case.
2. change the doAsSuperUser function from UserSynchronizer->synchronizeLdapUser to return return $userModel->getUser($piwikLogin); rather than the userModelAPI-getUser.   With this pull, getUser is stripping the auth_token field out of the user returned via an enrichUser call.
3. Based on the change in 2, make Base->makeSuccessLogin just use the $userInfo['token_auth'] value rather than the result of the call to the usersManagerAPI->getTokenAuth

I can submit this as a pull request if you would like.. or if you want any other help I am happy to contribute.

**Comment by mattab** [comment]
@kachenjr A PR would be awesome indeed. thanks!

**Comment by kachenjr** [comment]
@mattab @sgiehl I'm getting it ready now.  I have a question about the plugin though.  There is logic in this plugin that detects "non ldap" users in an effort to not update users in the database that exist and weren't put there by this plugin.  Is that a critical behavior?  That it is there means someone needed it, or thought it was needed, at some point.  I don't see a way to keep this functionality with out some major changes in this plugin, and probably in the core UserManager logic.  If there is no current reason to keep it, I'd like to refactor it out of the code to make it easier to maintain.

I looked at the Shibboleth plugin to see what it does, and it does not have a similar behavior.  If you login via that auth method, the user in the database is updated.  No check to see if it was put there by the plugin to start with.

**Comment by sgiehl** [comment]
Not sure if that behavior is still required. But you could use UsersManager
API setUserPreference to store a flag if the user was created with ldap or
not. Would also need a small update script to set that flag for already
created users aswell.

**Comment by kachenjr** [comment]
That's the fun part.. the way the core UsersManager is setup, it updates the entry on your behalf before you get a chance to see it.  So that would have to be a pre upgrade step of some sort to make that happen.  Once you're in the latest Piwik3.0 code, the {LDAP} prefix on the password is hidden behind the extra hash.   I'm still trying to understand the workflow where you'd have to worry about this kind of collision, with the easy work around of creating users that aren't in ldap for non-ldap users.

**Comment by mattab** [comment]
@sgiehl @kachenjr Counting on you for fixing this issue before Sunday midnight UTC (ie. in 36 hours ish) as this was the last issue we need to fix before 3.0.0 stable release. Thanks much :-) 

@kachenjr if you're interested to help us maintain LoginLdap going forward it would be awesome. Would be happy to give you commit access after your pull request, if you're interested!

**Comment by diosmosis** [comment]
Hi there, saw this by chance. I don't have time or the knowledge of what's been going on w/ Piwik 3 to help fix this, but the main use case (that I remember) for differentiating between LDAP users & non-LDAP users was that storing an MD5 hash of an LDAP user's password in Piwik was a security risk to some (since if cracked, an attacker would have access to different services using the same LDAP server).

Not sure, nor in a position to decide, if this is still valid. Though hopefully the information is useful :)

**Comment by kachenjr** [comment]
@diosmosis Thanks for the info.  Given the new hashing in the core, that particular scenario shouldn't be an issue anymore.  
@mattab @sgiehl I'll get something in today, would like someone to check it over and make sure I didn't miss something in the overall direction with security.

**Comment by sgiehl** [comment]
@kachenjr Imho a flag for ldap/non-ldap users is required to be able to sync users correctly. When LoginLdap plugin is installed some users might already exist. Those won't be synced with ldap or overwritten with ldap data if a user with the same login exists there.

**Comment by kachenjr** [comment]
@sgiehl Found another use for it as well.  When you run the generate-token-auth command from the console, it uses that as a failsafe for not regenerating the tokens for non ldap users.

**Comment by sgiehl** [comment]
Guess that command can be removed. Piwik 3 allows regenerating token auth from UI without changing the password, so imho there is no use for that anymore

**Comment by kachenjr** [comment]
OK.  I'm going to commit this in stages so that you can see what I did for each bit.   Initial change to get things "working", and then refactoring after that, including making the isLdapUser functionality work correctly.  The initial change will make that method just return true so that the user data will get synced.
I've not had to do anything with the travis-ci stuff as of yet, so I may need some assistance with the learning curve there given the time constraints..

**Comment by sgiehl** [comment]
feel free and go ahead. I'll try to give you assistance where possible. Will be available for the next two hours or so or I'll have a look at it tomorrow.

**Comment by kachenjr** [comment]
@sgiehl I was just getting ready to do a pull request, and I see you have a branch that a whole lot further along than I am :)  If there's anything I can do to help, please let me know.   Sorry I was slow getting changes out, this is my first foray in trying to contribute to an open source project and I didn't want to create a mess.

**Comment by sgiehl** [comment]
Tried to fix that as well. But I don't have LDAP server running and can't test the changes in my environment.  So the changes currently on rely on the test results (which don't work yet).
Do you have a Piwik instance with a running LDAP server where you can test that properly?

**Comment by kachenjr** [comment]
@sgiehl that I can help with.. After fumbling around trying to set it up I found this.
http://www.forumsys.com/en/tutorials/integration-how-to/ldap/online-ldap-test-server/

These settings get you going, and then you can login with the users listed.. such as
tesla   password

[LoginLdap]
use_ldap_for_authentication = 1
enable_synchronize_access_from_ldap = 0
enable_random_token_auth_generation = 1
new_user_default_sites_view_access = "all"
user_email_suffix = ""
required_member_of = ""
required_member_of_field = "memberOf"
ldap_user_filter = ""
ldap_user_id_field = "uid"
ldap_last_name_field = "sn"
ldap_first_name_field = "givenName"
ldap_alias_field = "cn"
ldap_mail_field = "mail"
ldap_password_field = "userPassword"
ldap_view_access_field = "view"
ldap_admin_access_field = "admin"
ldap_superuser_access_field = "superuser"
use_webserver_auth = 0
user_access_attribute_server_specification_delimiter = ";"
user_access_attribute_server_separator = ":"
instance_name = ""
ldap_network_timeout = 15
servers[] = "forumsys"

**Comment by kachenjr** [comment]
The actual settings you need.. 
[LoginLdap_forumsys]
hostname = "ldap.forumsys.com"
port = 389
base_dn = "dc=example,dc=com"
admin_user = "cn=read-only-admin,dc=example,dc=com"
admin_pass = "password"

**Comment by kachenjr** [comment]
@sgiehl I can still pull your branch down and check it out if it will help.  If there is documentation on how to run the tests locally, please point me to it and I'll see if I can help out there as well.  I'm new to PHP, usually a backend java, python, perl, etc, developer.  The code isn't the issue, but the tool sets for web development aren't in my skill set just yet.

**Comment by sgiehl** [comment]
you can execute the tests locally using the command `./console tests:run LoginLdap` within piwik directory.
Not sure if they will run using an external LDAP server

**Comment by kachenjr** [comment]
I get a database error, so I'm missing some bit of setting up phpuint.  It's trying to connect with user @USERNAME@ , which I'm assuming is a setting I have to configure somewhere.

**Comment by sgiehl** [comment]
Maybe you need to set the database credentials for the tests. See https://developer.piwik.org/guides/getting-started-part-1#enable-development-mode

**Comment by kachenjr** [comment]
Yep.. Just found that.  My search for @USERNAME@ wasn't broad enough.  Sorry for the n00b question.   I'll pull down your branch and see what I can do.

**Comment by sgiehl** [comment]
I'm done for today. There still seems to be an issuw with syncing the password. Need to have a look at those tests tomorrow.
If you find any bugs or see improvements, feel free to leave some comments. Cheers!

**Comment by kachenjr** [comment]
Looking at things, the whole ldapPassword field capability can come out.  The password is no longer linked to the token, so the only time the password matters is when the user has disabled the always use ldap option, where it stores the user's actual password and then falls back to ldap.
I have all that working with my last commit, pulling in your changes as well.  
The gist of it is that the synchronize user method must return the full user, which means calling the UserModel rather than API to get the user.  At that point, the token_auth field is there and can be used.
I'm setting up now to try and get the ldap tests running.

**Comment by sgiehl** [comment]
Had another look and seems you're right. I've changed my yode to use the model instead of API to fetch the user. Now most tests work again. I'll try to fix the rest now as well...

**Comment by kachenjr** [comment]
@mattab per earlier comment, I'd love to help.  This particular plugin is key to the use of Piwik at my company.  I've got a feature in mind that I would like to try and implement as well.   I would like the option to sweep the users and remove ones that are no longer in ldap, if they were originally an ldap user.  That shouldn't be too hard to come up with as a console task that can be scheduled.

**Comment by sgiehl** [comment]
@kachenjr Your help would be very welcome. Feel free to implement the suggested feature and create a Pull Request for it. If you want you can also help with one of the open issues (https://github.com/piwik/plugin-LoginLdap/issues) - not sure which of them are still valid, but maybe you are able to prove some of them - or with any other improvement you have in mind.
If you need any help, feel free to ping me!
