### ISSUE TITLE
Call to undefined method Piwik\Plugins\LoginLdap\Auth\LdapAuth::setAuthCode()

### ISSUE THREAD

**Issue by r3pek** [piwik/plugin-LoginLdap#154]
After installing the plugin on my Piwik instance (version 3.0.0), whatever field I try to change on the settings menu, I always get this error saying that there's a missing function in the code.

If it helps, I also have the Google Authenticator plugin installed.

**Comment by mattab** [comment]
@r3pek thanks for the report. Would you mind disabling Google Authenticator temporarily and check if the error still occurs?

**Comment by r3pek** [comment]
@mattab 
Yeah, disabling Google Auth remvoes the error (and btw, on 3.0.2 it doesn't even show the dashboard). Should I report this elsewhere?

**Comment by sgiehl** [comment]
Google Auth is currently not compatible with any other Login plugin, so this is a known issue. Not sure if I have some time soon to make it compatible
