### ISSUE TITLE
LoginLdap configuration show nothing after update to Piwik 3.0.0

### ISSUE THREAD

**Issue by bluikko** [piwik/plugin-LoginLdap#155]
After updating Piwik to 3.0.0 (and LoginLdap to 4.0.0), going to configuration -> LDAP shows nothing. There are just two white rectangles where the configuration content would normally be.

I do not see any relevant error in nginx log or php-fpm log.

This is a long-running installation, many years, and some files in plugins/Goals/Report needed to be deleted manually, for example...

Any ideas what to check?

Edit: tried uninstall + reinstall, delete tmp/cache. No change.

**Comment by bluikko** [comment]
Looking at the page source, everything for LoginLdap seems to be there. But it is not displayed by the browser. So it would seem to be some kind of CSS/HTML/JS issue with rendering the page.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/14869000/22172515/837c7adc-dfdb-11e6-9fa0-4c2cd314da1a.png)

The browser is latest Chrome (v 55), all relevant plug-ins like AdBlockers are disabled. It started to _work after clearing the browser data_ for following items: "Cached images and files" and "Hosted app data".

The page worked normally with Internet Explorer without clearing browser data.

**Comment by mattab** [comment]
Hi @bluikko 
So from your last comment it sounds like it is working so closing this issue
