### ISSUE TITLE
admin_pass config not blankable from within UI

### ISSUE THREAD

**Issue by mgrobelin** [piwik/plugin-LoginLdap#195]
While configuring the LDAP plugin I noticed, that blanking the "LDAP Password" field does not modify the `config.ini.php` accordingly. `admin_pass` remains set within the configuration file, w/o representing this in the UI. 

In contrast, the "LDAP Bind Username" field behaves as expected.

```ini
[LoginLdap_myds]
hostname = "ldaps://myds.local"
port = 636
base_dn = "dc=myds,dc=local"
admin_user = ""
admin_pass = "xxx" <<<- never gets blanked once set by UI
```

This lead to some unexpected results while testing (non-)anonymous binding.

I am using Matomo 3.13.0 and LoginLdap v4.0.8

**Comment by AltamashShaikh** [comment]
@mgrobelin The password is never updated if its blank same is mentioned in the helptext,  to explicitly update it to blank, I recommend you updating the `config.ini.php` file directly
![Screenshot from 2023-03-14 12-58-31](https://user-images.githubusercontent.com/14902277/224926709-682dba78-511b-4189-9ba5-a7d76ea6969d.png)
