### ISSUE TITLE
How to enable kerberos on IIS

### ISSUE THREAD

**Issue by nils-a** [piwik/plugin-LoginLdap#199]
Hi there,
is there any documentation on enabling kerberos when running on IIS? 
I've got multiple issues with it:

- `REMOTE_USER` always contains the netbios-login (i.e. `domain\user`) which is not available in ldap (i.e. Active Directory). This is partly addressed in #114, however for me it's no so simple as shown in #114. Netbios logins look like `company\user` while upn / email look like `user.fullname@company-worldwide.com`. So simple replacement is not an option for me.
- after activating "Windows Authentication" on IIS _every_ request needs to be authenticated, even the call to `/matomo.js` - I'm guessing that's also not really intended. Is there any documentation on which urls/areas should be protected and which should be available anonymously?

**Comment by iamdoubz** [comment]
Can't you just disable all forms of authentication except for Windows Authentication?

**Comment by nils-a** [comment]
@iamdoubz you mean like "deleting" everything authentication-related from the matomo-installation?

**Comment by iamdoubz** [comment]
If i understand your situation, you want to authenticate all of your Matomo traffic through AD. Is this correct? If it is, then in the IIS Manager under your Matomo install folder, disable all forms of authentication except for Windows Authentication. Something like this:

![iis_matomo](https://user-images.githubusercontent.com/4871781/101097758-610c8680-3587-11eb-8c0f-9e7b8890e798.png)

**Comment by nils-a** [comment]
This is the setup I have. However, having enabled that will require even accessing the `matomo,js` (and the tracking) to be authenticated requests.

**Comment by tomolimo** [comment]
Hello @nils-a 

You may check this post, where I explained how to set Windows authentication for some parts of a web site, and how to keep others with anonymous. This post is for GLPI, but it should be the same kind of solution for Matomo.
https://github.com/glpi-project/glpi/issues/8983#issuecomment-824624915

Thank you
Regards,
Tomolimo

**Comment by nils-a** [comment]
Thanks, @tomolimo that's probably the way to go: Enable Windows authentication for the site, then disable it for `matomo.js` (i.e. the [tracking client](https://developer.matomo.org/api-reference/tracking-javascript)) and `matomo.php` (i.e. the [tracking HTTP API](https://developer.matomo.org/api-reference/tracking-api))

Alas, I am unable to test this, since I abandoned the project to integrate this plugin into a matomo installation. But thanks for the idea.
