### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by Deltaminati** [piwik/plugin-LoginLdap#207]
Hi,

I am trying to install the LoginLDAP plugin on an offline installation.

I took the 4.8 zip version, renamed it "LoginLDAP" and copied it to the /matomo/plugins folder.

I have the following php error whenever I try to activate the plugin :

"Uncaught exception: Error: Class 'Piwik\Plugins\LoginLDAP\API' not found in [installation folder]/matomo/plugins/LoginLDAP/Commands/SynchronizeUsers.php:44"

Thank you in advance for reading.

Regards,

Deltaminati.

**Comment by sgiehl** [comment]
Hi @Deltaminati. Sorry for the long delay. Actually I think that might be a naming issue. The plugin is called `LoginLdap`. So putting it in a directory called `LoginLDAP` might not work depending on the filesystem / os.
