### ISSUE TITLE
Changing name of server doesn't work

### ISSUE THREAD

**Issue by ghost** [piwik/plugin-LoginLdap#215]
First of all, I'd like to thank you for the job you've done :-) As I encountered a problem when setup this plugin, I'd like to share it so you can fix it and other could somehow deal with it.

When I setup an LDAP server, I can setup the URL, port number, base DN and alike but If i change the server name, your plugin fails to connect to the ldap server. Whatever tool I use to test ("Test" button in the "ldap parameter" web gui or the command lines in the troubleshouting page), I get the following exception : `No LDAP servers configured in LdapUsers instance.`

To "fix" it, just use the default server name (i.e. "server1") and it works.

For information, here are the version number of Matomo and ldap plugin

* **Matomo :** 3.14.1
* **Login Ldap :** 4.0.8

**Comment by Thatoo** [comment]
same issue

**Comment by AltamashShaikh** [comment]
@tbowan @Thatoo Do you still face the issue with latest version of the plugin ?

**Comment by Thatoo** [comment]
Yes but it doesn't bother me as I have only one ldap server and I don't mind its name being simply "server" in Matomo :-)
I actually don't really understand the point of this field.

**Comment by AltamashShaikh** [comment]
@Thatoo I just tested this on `4.7.1` version of the plugin and seems to work for me
![Screenshot from 2023-03-23 08-39-23](https://user-images.githubusercontent.com/14902277/227091713-fce6f012-b0e1-4b97-998f-2542bec7ff0c.png)

**Comment by AltamashShaikh** [comment]
@Thatoo You need to update the password too, just changing the name won't copy the password

**Comment by Thatoo** [comment]
It's ok, I don't need to change the name and I don't want to bother changing the password everywhere just to test if it works now.
