### ISSUE TITLE
Add support for Matomo >= 4.0.0

### ISSUE THREAD

**Issue by iamdoubz** [piwik/plugin-LoginLdap#221]
I am currently using IIS and Matomo version 3.14.1.

Thank you for a wonderful plugin and all the hard work put into it.

**Comment by Leboubou111** [comment]
I've updated Matomo to v4.0.4 and LoiginLdap plugin to v4.2.2.
But, after active it, I've a blank page on plugin configuration page.
I've tried to disable and enable it again, same issue.

![image](https://user-images.githubusercontent.com/8314926/101143780-abd5df00-3617-11eb-89fd-4f72609848df.png)

**Comment by sgiehl** [comment]
@Leboubou111  can you see any errors in the browser console?

**Comment by Leboubou111** [comment]
![image](https://user-images.githubusercontent.com/8314926/101145762-88606380-361a-11eb-8d53-3ec45e68e044.png)

I don't know if this can help you...

**Comment by Leboubou111** [comment]
Apparently on this function

function g(a,c,d,e){var f,k,l,m,p,I,t;if(n)for(t=Array(c.length),m=0;m<h.length;m+=3)f=h[m],t[f]=c[f];else t=c;m=0;for(p=h.length;m<
p;)k=t[h[m++]],c=h[m++],f=h[m++],c?(c.scope?(l=a.$new(),da.$$addScopeInfo(x(k),l)):l=a,I=c.transcludeOnThisElement?ka(a,c.transclude,e):!c.templateOnThisElement&&e?e:!e&&b?ka(a,b):null,c(f,l,k,d,I)):f&&f(a,k.childNodes,void 0,e)}

**Comment by Leboubou111** [comment]
And this one :

a&&a(R,f.childNodes,void 0,l);

**Comment by sgiehl** [comment]
Are there any failing requests in the network tab when loading the page?

**Comment by Leboubou111** [comment]
No, all request on Network Tab return 200 status code.
In the console tab, error message display this link :
https://code.angularjs.org/1.8.2/docs/error/$controller/ctrlreg?p0=LoginLdapAdminController

**Comment by iamdoubz** [comment]
I did not update because Matomo told me explicitly that it would not work with version 4.0.3 (now 4.0.4).

![matomo_ldap](https://user-images.githubusercontent.com/4871781/101205666-97074480-3633-11eb-9dd1-bf857dd9f15e.png)

**Comment by tsteur** [comment]
Hi @iamdoubz it's only saying it will upgrade the plugins. The shown requirements are their current requirements (could be made more clear)

**Comment by iamdoubz** [comment]
Oic. So, in your opinion, the plugin should already be fully compatible with 4.0.4?

**Comment by tsteur** [comment]
Yes 👍

**Comment by tsteur** [comment]
I'll close this issue. Let us know if there's any problem with it @iamdoubz

**Comment by iamdoubz** [comment]
I do want to report back just to say that I upgraded successfully and Matomo automatically upgraded LoginLdap to the latest version and everything works perfectly.

**Comment by Leboubou111** [comment]
Great... And if you try to access plugin configuration page ? Do you have something ?

**Comment by iamdoubz** [comment]
Yes I do. The LDAP option is populated as expected.

**Comment by Leboubou111** [comment]
After update to 4.1.0, works fine ;-)
Thanks for your job.
