### ISSUE TITLE
"Remember Me" not keeping users logged in

### ISSUE THREAD

**Issue by paladox** [piwik/plugin-LoginLdap#222]
We use Matomo 4 (this issue also happened with matomo 3). Matomo keeps logging me out after a while even though I clicked "remember me". We use the LoginLdap plugin though (as we use Ldap for logins).

Could this be fixed please?

**Comment by paladox** [comment]
Could this be because of https://github.com/matomo-org/matomo/blob/7585967cbd80d7869f57a9adc69c02e8d14cbc33/core/Session/SessionInitializer.php#L28 not including "remember me" compared to https://github.com/matomo-org/matomo/blob/7585967cbd80d7869f57a9adc69c02e8d14cbc33/plugins/Login/SessionInitializer.php#L100 ? ( @tsteur )

**Comment by heurteph-ei** [comment]
The same as #206 ?

**Comment by paladox** [comment]
Yeh
