### ISSUE TITLE
Bind username - min access level

### ISSUE THREAD

**Issue by WarrenG2025** [piwik/plugin-LoginLdap#233]
What is the minimum level of access this user needs? I really don't want to use an AD Admin account just to authenticate logins?

**Comment by flamisz** [comment]
Hi @adm-guerinw, unfortunately, we don't answer questions in this issue tracker but only handle feature requests or bug reports. We'd greatly appreciate it if you asked the question in our forum: https://forum.matomo.org/. Thanks for your understanding.
