### ISSUE TITLE
Releases and Matomo version dependency

### ISSUE THREAD

**Issue by bluikko** [piwik/plugin-LoginLdap#280]
It seems LoginLdap 4.5.0 requires "Matomo >=4.10.0-b1".

Is it on purpose that released LoginLdap requires a beta version of Matomo? And that this is not listed in release notes?  
Is it expected that users of LoginLdap look at diffs of new versions before updating? Perhaps updating through Matomo web interface does some dependency check but I do not know anyone anymore who manages things like this manually and not with automation. The `console` does not provide an update functionality that would be dependency aware. So we are stuck downloading the plugin and doing it ourselves since Matomo is very automation-unfriendly by design.

Wouldn't it make sense to mark versions that depend on an unreleased/beta version of Matomo as "pre-release" in GitHub?  
Looking to open discussion on how breaking systems could be avoided in the future.

**Comment by AltamashShaikh** [comment]
@bluikko The new Matomo version would be released in few days, we would make sure from next time to not release before core update.

**Comment by bluikko** [comment]
I see, thanks. I guess in the long term we will then parse `plugin.json` for `require.matomo`.
