### ISSUE TITLE
Emailed 'accept invite' link doesn't work

### ISSUE THREAD

**Issue by grandpaslab** [piwik/plugin-LoginLdap#298]
LoginLdap requires that you turn off the default Login plugin, which is required for the 'accept invite' link to work. When clicking the link, users see an error "The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Matomo."

**Comment by AltamashShaikh** [comment]
@grandpaslab I can reproduce this bug, will see if we can provide a fix for this

**Comment by AltamashShaikh** [comment]
Steps to reproduce the bug
1. Activate and setup LDAP plugin
2. Create a new user and try to create click on the invite link and you will see the below error
![Screenshot from 2022-09-09 08-51-18](https://user-images.githubusercontent.com/14902277/189265313-c6276c5f-29ef-4457-93d2-05b01bd9f7dd.png)

**Comment by AltamashShaikh** [comment]
@grandpaslab Just a workaround, can you use this [API](https://developer.matomo.org/api-reference/reporting-api#UsersManager) to create the users till we find a solution ?

**Comment by AltamashShaikh** [comment]
Created - https://github.com/matomo-org/matomo/issues/19717

**Comment by AltamashShaikh** [comment]
@grandpaslab should be fixed with release of Matomo 4.12
