### ISSUE TITLE
False-positive "required private directories" error

### ISSUE THREAD

**Issue by grandpaslab** [piwik/plugin-LoginLdap#299]
With Kerberos/REMOTE_USER auth enabled, system check reports a false-positive error:

Required Private Directories:
        - ERROR https://matomo.sandwich.com/config/config.ini.php
        - ERROR https://matomo.sandwich.com/tmp/cache/tracker/matomocache_general.php
Recommended Private Directories:
        - ERROR https://matomo.sandwich.com/tmp/
        - ERROR https://matomo.sandwich.com/tmp/empty
        - ERROR https://matomo.sandwich.com/lang/en.json
        - INFORMATIONAL We found that the above URLs are accessible via the browser, but we recommend they should not be. If possible, please restrict access to them. Read this to learn more.

These directories are not accessible through the browser on my install. With REMOTE_USER auth disabled, system check correctly reports no error.

**Comment by AltamashShaikh** [comment]
@grandpaslab the setting is very unrelated to the diagnostic check and I did check in code and we are not adding/updating anything related to diagnostic check.

Try doing this from you console and check the HTTP status when the setting is enabled, I doubt it will make any difference
`curl -I "https://matomo.sandwich.com/config/config.ini.php"`

**Comment by grandpaslab** [comment]
I just realized this false positive is because I'm running mod_auth_mellon for Okta auth. So when the system check loads /config/ or whatever, it does get a response. System check should be smart enough to check the response against the request, or it will return false positives when it's redirected to an auth page like Okta. So I guess this bug is for the core matomo project, not LoginLdap. I'll close this one and write it up there.
