### ISSUE TITLE
Feature Request: enable both Login Ldap and Normal Login plugin at the same time.

### ISSUE THREAD

**Issue by sgreiner** [piwik/plugin-LoginLdap#301]
I noticed that normal users can no longer login, after the Login LDAP plugin was enabled.

Is it possible to assign a user a Login Plugin and have both plugins enabled at the same time?
We have employees who use our matomo instance and also have external users who do not exist in our AD but have access to some sites. Currently they cannot login.

Used Login Ldap Version: 4.5.2

**Comment by AltamashShaikh** [comment]
Hey @sgreiner,
That’s not possible currently but if LDAP fails it fallbacks to normal login.

I currently have few users created directly and few are being logged in via ldap auth.

can you share your settings?

**Comment by sgreiner** [comment]
Hey @AltamashShaikh, 

thank you for your fast response :-)
My description was indeed not correct. There is a fallback for existing users.

The problem is the user creation process: I click on: invite new user, fill out their mail and they get an email to accept the invitation. But then the get an error that the "Login" plugin is not enabled:

![image](https://user-images.githubusercontent.com/2290942/190668181-721f7151-ff0e-482f-806f-fc3a85f00214.png)

![image](https://user-images.githubusercontent.com/2290942/190666366-0f26ad52-a328-44c3-bc6f-667956b93ea8.png)

![image](https://user-images.githubusercontent.com/2290942/190666094-ea595c34-387e-4d4a-92f5-c16278b1c60a.png)

Then I temporarily as a workaround enabled both plugins (which should not be done, it gives a warning) and then they could accept invitation. After that I disabled the normal Login plugin again and the newly created external user can indeed login.
![image](https://user-images.githubusercontent.com/2290942/190666593-7c4d334f-bfa1-4bfd-9880-f267ef193007.png)

I remember that I could create users without invitation in the past, but that option seems to be gone.
Maybe you have any advice?

**Comment by AltamashShaikh** [comment]
Hey @sgreiner 
This issue will already be fixed in Matomo 4.12 and post updating to Matomo 4.12 this feature will work again
https://github.com/matomo-org/matomo/pull/19718
