### ISSUE TITLE
LDAP Server name with spaces breaks config

### ISSUE THREAD

**Issue by lscorcia** [piwik/plugin-LoginLdap#304]
Hi, I just noticed that if I put a space in the server name (e.g. "AD LDAP"), the server details config section in the ini file is created without spaces ("ADLDAP") but the server name is saved as is in the main config. This makes logins fail and in the log file the plugin says it cannot retrieve the server configuration.

An easy fix would be to disallow spaces in the server name.

**Comment by AltamashShaikh** [comment]
Hey @lscorcia Thanks for creating this issue and I can confirm this is a bug

**Comment by AltamashShaikh** [comment]
@lscorcia will you be able to apply this patch ?
https://github.com/matomo-org/plugin-LoginLdap/pull/305/files

**Comment by AltamashShaikh** [comment]
@lscorcia Should be fixed with release of new version of the plugin

**Comment by AltamashShaikh** [comment]
@lscorcia Released 4.5.4 version of the plugin.
