### ISSUE TITLE
admin_pass escaping breaks configuration

### ISSUE THREAD

**Issue by scullytr** [piwik/plugin-LoginLdap#308]
Took awhile to figure this one out, but the escaping that happens on the admin_pass parameter breaks the configuration if the password contains a single-quote character (and potentially others).

**Comment by snake14** [comment]
Hi @scullytr . Thank you for taking the time to create this issue. I have updated the code so that it should properly handle escaped characters, like single quotes. This change should be included in the next release of the plugin.

**Comment by scullytr** [comment]
Awesome, thanks so much @snake14!
