### ISSUE TITLE
Add option to disable Password Confirmation

### ISSUE THREAD

**Issue by Starker3** [piwik/plugin-LoginLdap#310]
# Proposed steps

- disable the password confirmation prompt by default for LDAP
- introduce new plugin setting to enable the password confirmation prompt (similar to how we did for SAML)

# Original issue

Similar to other SSO login options, users of the LoginLdap plugin would like to have the option to not have to enter a password confirmation in the UI. Since it's now possible to disable the password prompt with this change: https://github.com/matomo-org/matomo/pull/19525

It would be great for some Matomo admins to have this option. Since disabling the password prompt would in some cases be less secure, maybe having an option in the UI to disable the password confirmation or have a config.ini.php option to disable it would be very useful but still keep it enabled by default.

**Comment by AltamashShaikh** [comment]
@Starker3 closing this, since this was implemented in - https://github.com/matomo-org/plugin-LoginLdap/pull/320
