### ISSUE TITLE
Database update for version 4.7.2 failed

### ISSUE THREAD

**Issue by DalbertHab** [piwik/plugin-LoginLdap#334]
After updating the plugin, we had to update the database. During the update we git the error message `* SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'option where option_name like '%_isLDAPUser'' at line 1`.

After debugging the code, the problem occurs as we use no prefix for the tables and **option** is a reserved keyword in mysql [MySQL Keywords](https://dev.mysql.com/doc/refman/8.0/en/keywords.html).

After changing the SQL statement, everything went smoothly:

OLD: $optionValues = $db->fetchAll("Select option_name from **$optionTable** where option_name like '%$searchPattern'");
NEW: $optionValues = $db->fetchAll("Select option_name from **\`$optionTable\`** where option_name like '%$searchPattern'");

**Comment by AltamashShaikh** [comment]
@DalbertHab Sorry, I should have thought about it, will release a new version with the fixed script

**Comment by AltamashShaikh** [comment]
@DalbertHab Should be fixed with release of 4.7.3 version

**Comment by DalbertHab** [comment]
Thanks :)
