### ISSUE TITLE
Synchronize LDAP user deletion

### ISSUE THREAD

**Issue by heurteph-ei** [piwik/plugin-LoginLdap#339]
I searched during a long time because I remember this topic has already been mentioned somewhere, but unfortunately I did not found it... 😞 

When LDAP users are removed form the LDAP, the deletion is not synchronized in Matomo. Then the feature request is to synchronize the user deletion.

Matomo version: 4.3.1
PHP Version: 7.3.33
LoginLdap version: 4.3.0

**Comment by AltamashShaikh** [comment]
@heurteph-ei There is a pending PR #205 for this feature

**Comment by heurteph-ei** [comment]
Hi @AltamashShaikh,
I see the PR has been merged, then I think this ticket can be closed now...
