### ISSUE TITLE
Emailed Reset-Password-Link does not link to te correct Login-Module

### ISSUE THREAD

**Issue by wlma** [piwik/plugin-LoginLdap#340]
Similar to #298 the Reset password link in the Mail does not link to module "LoginLdap" but to "Login 

https://<domain>/index.php?module=Login&action=confirmResetPassword&login=testuserit&resetToken=8da2c29f0495e0ad7dc021114ec807e9c65395d292a55eaf8c7b926bb725f5f27aa64c1a2df7f7c9986ac23004a8ba0c479f13bef76ac04d25b784b2728068ae

Tested on 4.14.1

**Comment by AltamashShaikh** [comment]
@wlma I can reproduce this issue, unfortunately it will require a fix in Matomo core, will check and update you

**Comment by AltamashShaikh** [comment]
@wlma Created https://github.com/matomo-org/matomo/pull/21017 to solve the issue

**Comment by AltamashShaikh** [comment]
@wlma 4.x version should be fix by this [PR](https://github.com/matomo-org/matomo/pull/21018)
