### ISSUE TITLE
Matomo 5.0.1 Updater does not recognize LoginLdap available for Version 5

### ISSUE THREAD

**Issue by kingfisher77** [piwik/plugin-LoginLdap#361]
Thanks for this useful Plugin!

The updater for Matomo does not recognize LoginLdap available for Matomo Version 5:

```
Note: some plugins are not compatible with Matomo 5.0.1. We will update them if there is an update on the Marketplace, otherwise we will disable them when you upgrade:

GroupPermissions
LoginLdap
```

When will the updated plugin be available?

**Comment by AltamashShaikh** [comment]
@kingfisher77 The message is a bit confusing and we already have a [issue](https://github.com/matomo-org/matomo/issues/21842#issuecomment-1907142743) in Matomo core to improve it. As the message states "We will update them if there is an update on the Marketplace" and there is already an update available for both the plugins for Matomo 5, you should be able to update without any hassle :+1:
