### ISSUE TITLE
Could not bind as LDAP admin

### ISSUE THREAD

**Issue by hunterelectros** [piwik/plugin-LoginLdap#388]
Hello!
We try to setup LDAP authorization in Matomo. For debugging we use a non-docker version of the installation. Apache2.4, php8.3 (with all necessary extensions).
During the debugging process, we reached the point where the debug script works the same way both in the console and in the browser - Query count: 4000.
<?php
$ldapUri = <ldap_uri>;
$baseDn = <basedn>;
$adminBind = <admin_bind>;
$adminPwd = <admin_pwd>;
$connection = ldap_connect($ldapUri);
if (empty($connection)) {
    echo "ERROR: Failed to connect to '$ldapUri'.\n";
    exit(1);
}
ldap_set_option($connection, LDAP_OPT_PROTOCOL_VERSION, 3);
ldap_set_option($connection, LDAP_OPT_REFERRALS, 0);
$bindResult = ldap_bind($connection, $adminBind, $adminPwd);
if (!$bindResult) {
    echo "ERROR: Failed to bind to '$adminBind'!\n";
    exit(1);
}
$result = ldap_search($connection, $baseDn, '(objectClass=person)');
if (empty($result)) {
    echo "ERROR: Got empty ldap_search result '$result'!\n";
    exit(1);
}
$count = ldap_count_entries($connection, $result);
echo "Query count: $count\n";
?>
Also, ldapsearch works fine.
 But still, after running command in CLI "php ./console loginldap:synchronize-users --login=%username%" we receive "Could not bind as LDAP admin."
Please help us)

**Comment by snake14** [comment]
Hi @hunterelectros . I'm sorry that you're experiencing this issue. Have you searched the [Matomo forum](https://forum.matomo.org)? Are you sure that you have the correct LDAP Bind Username configured in the application? For example, the value that I use in my testing instance is `cn=admin,dc=test-ldap,dc=local`.

Have you tried running `php ./console loginldap:synchronize-users --login=%username%` with the `-vvv` option to get more debugging information? When I do that, I can see the following line in the output:
```
DEBUG     [2024-12-19 21:03:42] 403127  ldap_bind result is '1'
```
Any other recommendations @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@hunterelectros For your reference, this is what my config looks like, check if you haven't enabled tls or try running the command with `-vvv` as suggested by @snake14 to get more info.

![image](https://github.com/user-attachments/assets/cb2a8ccf-1009-49fc-a0bd-feed4c6c9269)
```

**Comment by hunterelectros** [comment]
Hello! I searched the Matomo forum, and don't find anything, maybe I didn't search well. We use ActiveDirectory. Maybe user ta_jirasm_adsync (what we use) need to some special rights. But this user has read permissions and we use it in our Jira, everything works.
![Screenshot_23](https://github.com/user-attachments/assets/373f8cd7-d40d-408f-979b-476364412ece)

php ./console loginldap:synchronize-users --login=ta_jirasm_adsync -vvv
Could not bind as LDAP admin.

php ldap.php    (debug script) - PHP Warning:  ldap_search(): Partial search results returned: Sizelimit exceeded in /var/www/html/ldap.php on line 23
Query count: 4000
Our settings in Matomo. LDAP Bind Username - CN=ta_jirasm_adsync,OU=Jira,OU=Technical Accounts,OU=_CORP,OU=ONE,DC=pt,DC=playtech,DC=corp
![Screenshot_24](https://github.com/user-attachments/assets/6208a426-5075-4f2e-9cb7-7bf91c115928)

**Comment by AltamashShaikh** [comment]
@hunterelectros does changing the port to 389 works ?

**Comment by hunterelectros** [comment]
We don't use 389 port (LDAP without SSL). Only 3269 with SSL...

**Comment by AltamashShaikh** [comment]
@hunterelectros I was just searching your issue found this links, with similar problem

https://www.php.net/manual/en/function.ldap-bind.php#86635


https://forum.matomo.org/t/loginldap-with-ssl/31575

or you can try running the ldap search [command](https://github.com/matomo-org/plugin-LoginLdap/wiki/Troubleshooting#checking-for-an-ldap-server-configuration-issue) via cli and check if it works.

**Comment by hunterelectros** [comment]
Hello! Thanks to everyone for the tips. In my case, everything turned out to be simpler - incorrect settings for connecting to ldap, incorrect search filters. Well, and most importantly - in docker, php stubbornly refuses to connect to ldap, even when I ran test debug scripts. In docker, they do not work, in a normal environment (not in docker), everything works.
