### ISSUE TITLE
LoginLdap Unable to recogize users in lower level groups

### ISSUE THREAD

**Issue by alboss17** [piwik/plugin-LoginLdap#85]
Currently using loginldap plugin and its the unable to find users 1 level down from the Base DN.  Its seems as if the ldap call isn't traversing through the child AD Groups within the Base DN.  Is there  a setting that I need to check to correct this?

**Comment by diosmosis** [comment]
It's possible LoginLdap doesn't support this use case, but I'm not quite sure. Can you post your config w/ sensitive information removed (ie, passwords)?

**Comment by alboss17** [comment]
Config information below:

LDAP Settings
Always use LDAP: Y
Synchronize: Y
Web Auth: N
LDAP Network Timeout: 15
Required user Group: "Blank"
Ldap Search Filter: (objectClass=*)

User Sync
User ID Field: samaccountname
user password file: userPassword
email: mail
user Alias: cn
first name; givenName
last name: sn
email address suffice: @comany.com
initial sites: 1

Access Sync Settings
Enable User Access Sync from LDAP: N

LDAP Servers
Server URL:  ldaps://test.us.company.com
Port: 369
Base DN: DC=US, DC=COMPANY, DC=COM
username: CN=myuser......

**Comment by alboss17** [comment]
Hello, thanks for the quick response.   I just wanted to see if you had a chance to investigate the above issue. Thanks again

**Comment by diosmosis** [comment]
After re-reading your initial post I may need more information (unless my initial understanding is correct). Do you mean you are trying to authenticate users whose base DN is different than in your config (eg, config has 'dc=example,dc=com', users have 'dc=us,dc=example,dc=com')? If so I don't think this is possible going through LDAP, as I believe data for each base DN is stored in separate databases. According to this article: https://technet.microsoft.com/en-us/library/cc978012.aspx, however, if you search through the global catalog, you can access users from separate base DNs. Setting the port to 3268 should search through the global catalog.

If not, can you please elaborate?

**Comment by alboss17** [comment]
Here's  are a few examples:
IF BaseDN is (dc=example, dc=com)  AND UserDN = (dc=example, dc=com)  THEN
   All users with that same Base DN are found successfully
IF BaseDN is (dc=example, dc=com') and UserDN = (dc=us,dc=example,dc=com) THEN
   No users are able to be found
IF BaseDN is (dc=us, dc=example, dc=com) and (UserDN = (dc=example, dc=com) OR UserDN=(dc=us,dc=example,dc=com))
   No users are able to be found

My issue is that the ldap plugin on can find users at the highest level of the DN.  Our other ldap tools (including LDAP browser) are able to find users at all levels of our DN.  I've also tried changing the port with not success.  Is there a flag or a setting that I can force the ldap plugin to search in sub groups?  Or is there a php method that I could add some logging to so I could debug why its only finding users in the highest level of our DN?

**Comment by alboss17** [comment]
I think I may have found the bug.  Ldap Plugin seems to be ignoring the specified Server Port value, so I added it directly to URL and now I'm able to search/find users in all DN's.

**Comment by diosmosis** [comment]
I created a separate issue for the port bug: https://github.com/piwik/plugin-LoginLdap/issues/87

After some tests I determined the current code allows your required use case when the backend is OpenLDAP. This appears to be a ActiveDirectory/configuration issue, so I'm closing. ActiveDirectory users should use the global catalog.
