### ISSUE TITLE
authenticateByPassword: empty login encountered.

### ISSUE THREAD

**Issue by surfi2000** [piwik/plugin-LoginLdap#90]
LoginLdap version 3.1.3
Piwik version 2.11.1

Receiving multiple of the below errors across all UI's

WARNING LoginLdap[2015-02-23 23:26:10] [2bd96] authenticateByPassword: empty login encountered.

**Comment by thomykay** [comment]
Same here after piwik/LoginLdap update. After login I see "user with same name exists" and then I see multiple "WARNING LoginLdap[...] [...] authenticateByPassword: empty login encountered." in most/all pages.

**Comment by reynlds-illinois** [comment]
This is happening for both LDAP and non-LDAP logons for instances using this plugin, and only on the Administration pages (so far).

**Comment by surfi2000** [comment]
This happens on both Administration pages and general pages

**Comment by reynlds-illinois** [comment]
I was able to clear the error by logging in then out as a non-LDAP user, then logging in as an LDAP user. No more error on any page.
