### ISSUE TITLE
LoginLdap breaks piwik 2.11.1 (also maybe 2.11) login screen

### ISSUE THREAD

**Issue by ArnY** [piwik/plugin-LoginLdap#91]
since upgrading to piwik 2.11.1 piwik's login screen is (visually) broken: 

cf https://github.com/piwik/piwik/issues/728

**Comment by diosmosis** [comment]
Can you post a screenshot?

**Comment by reynlds-illinois** [comment]
![piwik-broken-logon-screen](https://cloud.githubusercontent.com/assets/2440061/6352209/a271714a-bc06-11e4-9ba7-a9017b4ff968.PNG)

**Comment by diosmosis** [comment]
Ok, thanks! I'll fix it as soon as I can.
