### ISSUE TITLE
Cannot connect to Active Directory :(

### ISSUE THREAD

**Issue by gazdajezda** [piwik/plugin-LoginLdap#92]
Hello!

I try to connect Piwik 2.12.1 + LoginLdap (v3.1.4) to Windows 2008 Active Directory with half success. In configuration tab (LDAP) i entered our data and i can use test link with "Required User Group" and "LDAP Search Filter" field. It works and correctly return number of users which match criteria. But i cannot login with AD users (like gazdajezda@my.domain.ad or AD\gazdajezda). In fact, it is confusing, since i can query AD (in setting), but on the top of the page there is warning:

The PHP LDAP extension does not appear to be enabled. It is required for this plugin, please install it.

I have enabled PHP_LDAP extension in php.ini. Please, do anyone have similar problem? How can i resolve it? 

Thank you for any answer.

**Comment by diosmosis** [comment]
Can you post your LDAP settings (w/ sensitive information redacted, screenshot would suffice), and do the following:

1) enable debug logging by adding the following to your config.ini.php:

```
[log]
log_writers[] = file
log_level = DEBUG
logger_file_path = tmp/logs/piwik.log
```

2) try to login
3) email the log file in tmp/logs/piwik.log to hello@piwik.org

**Comment by gazdajezda** [comment]
@diosmosis: of course, here it is. I overtype password's, other stuff is valid.

![piwik-ldap-01](https://cloud.githubusercontent.com/assets/11771422/6978812/230228ea-d9da-11e4-9fe7-7dcc0e6e1b7a.gif)

I also send this image, my ini and log file via mail to ciao@Piwik (actually hello)
Hope it will help :)

Regards, Gazda

**Comment by gazdajezda** [comment]
And if it is of any help, also system check done by Piwik.

![piwik-system-check](https://cloud.githubusercontent.com/assets/11771422/6978985/9538951e-d9dc-11e4-9567-cc5a54947b3b.gif)

**Comment by gazdajezda** [comment]
Also, php_ldap IS enabled in php.ini ;)

![piwik-php-ldap](https://cloud.githubusercontent.com/assets/11771422/6979009/f28504a0-d9dc-11e4-9c48-77266843c05f.gif)

If there is something else i can do, np :)

**Comment by diosmosis** [comment]
Hi @gazdajezda, I looked through the log file you sent, but I can't find authentication logs, though LoginLdap is obviously enabled properly.

Assuming you tried to login w/ an LDAP user while debug logging was enabled, then it might be possible that the plugin can't find the ldap_connect function which is aborting the login process. Can you run `<?php echo "function exists: " . function_exists('ldap_connect') . "\n";` through php-fpm (or through php-cgi if that's what you use) and see if the function exists?

Also, could you try to run the following console command and email the results?

`./console loginldap:synchronize-users --login=gazdajezda@my.domain.ad -vvv`

**Comment by gazdajezda** [comment]
Hi Benaka!

First, very thank you for your answer. I would like to try anything you
wrote, because i really wann't to get Piwik work with our AD.

I create a PHP file with following content:

<?php
echo "function exists: " . function_exists('ldap_connect') . "\n";
;

and when i open it in browser i get:

function exists: 1

Second command returns me nothing for AD user tomi@ad.intranet.tmd:

C:\Users\Administrator>php -r ./console loginldap:synchronize-users
--login=tomi@ad.intranet.tmd -vvv
C:\Users\Administrator>

Without -r switch:

C:\Users\Administrator>php ./console loginldap:synchronize-users
--login=tomi@ad.intranet.tmd -vvv
Could not open input file: ./console

Maybe i don't properly run the command?

Is that information of any use to you?

With best regards!


2015-04-07 23:02 GMT+02:00 Benaka <notifications@github.com>:

**Comment by gazdajezda** [comment]
I also try to manually synchronize that user, but no go:

[image: Slika v vrstici 1]

Regards!

2015-04-09 10:02 GMT+02:00 <gazdajezda@gmail.com>:

**Comment by diosmosis** [comment]
> C:\Users\Administrator>php ./console loginldap:synchronize-users
> --login=tomi@ad.intranet.tmd -vvv
> Could not open input file: ./console
> 
> Maybe i don't properly run the command?

Is your piwik installation in `C:\Users\Administrators`? `console` is a file in the piwik home directory, so if your Piwik is in `C:\piwik`, you should run:

`php C:\piwik\console loginldap:synchronize-users --login=tomi@ad.intranet.tmd -vvv`

Unfortunately at the moment this looks like a server configuration issue, and a hard issue to diagnose. If the command above doesn't provide a clear error message, you may have to do some debugging. I'll let you know what to do, but it could take a while.

**Comment by gazdajezda** [comment]
Aha, all clear about console :) So i start:

d:\Web\MasterSite\served\piwik>php ./console loginldap:synchronize-users
--login=tomi@ad.intranet.tmd -vvv > benaka.log

Content of benaka.log is attached. I really hope it will be of any help. I
don't care if it will take time, because i really wann't to use Piwik. I
will try anything you will suggest to get it working properly.

With best regards!

2015-04-10 2:11 GMT+02:00 Benaka <notifications@github.com>:

**Comment by diosmosis** [comment]
Fyi attachments don't appear in github. If you want to email the log, make sure to email to hello@piwik.org.

**Comment by gazdajezda** [comment]
No problem, did you get it now?

2015-04-10 10:17 GMT+02:00 Benaka <notifications@github.com>:

**Comment by diosmosis** [comment]
In the settings, can you change the filter to `(objectClass=person)` and try running the command again? If it works, try logging in.

**Comment by gazdajezda** [comment]
Hi!

I change parameter LDAP Search Filter to:

   - (objectClass=person) & SAVE (if i try, filter works)
   - then restart IIS
   - try to login with AD user, but there is still: Error: Wrong Username
   and password combination.

I look in AD if there are any other security setting, which prevent Piwik
access, but i cannot find anything usefull... Also it's strange - filter
works, loading user don't...

With best regards!

2015-04-11 2:18 GMT+02:00 Benaka <notifications@github.com>:

**Comment by gazdajezda** [comment]
I also run:

d:\Web\MasterSite\served\piwik>php ./console loginldap:synchronize-users
--login=tomi@ad.intranet.tmd -vvv > benaka2.log

And now, log is different, but still user not get synchronized. Content of
benaka2.log is attached.



2015-04-13 13:26 GMT+02:00 <gazdajezda@gmail.com>:

**Comment by diosmosis** [comment]
From a quick look at the logs you sent, it looks like the plugin can successfully connect & query LDAP, but for some reason either no user is found or the plugin ignores the user. I'll take a closer look soon.

**Comment by diosmosis** [comment]
In an LDAP client, can you check whether the `(&(objectClass=person)(uid=tomi@ad.intranet.tmd))` query returns results? What about `uid=tomi@ad.intranet.tmd`? 

The plugin attempts the first query, but it returns no results. If the queries don't work in another client, then maybe the "User ID Field" setting needs to be different (ie, userPrincipalName or sAMAccountName).

**Comment by gazdajezda** [comment]
Well, that's it, i believe. I look in LDAP Browser (Softerra or something)
amd i cannot find UID field in Users CN, but userPrincipalName is there, so
i change "User ID Field" to "userPrincipalName" and it seems that it is
working now. I can login with my username:

You are logged in as 'tomi@ad.intranet.tmd' but it seems you don't have any
permission set in Piwik.
Ask your Piwik administrator (click to email) to give you 'view' access to
a website. ...
Then i set permission to view particular site, so now i believe it works. I
can now try to see if it is all what we need instead of some other big
analytics software :) Thank you for helping me solve the problem! Can i buy
you a beer? If yes, how?

With best regards!

2015-04-13 23:30 GMT+02:00 Benaka <notifications@github.com>:

**Comment by diosmosis** [comment]
> Can i buy you a beer? If yes, how?

Thanks for the offer :) but I don't use any of the developer donation sites (or whatever they are called).

**Comment by gazdajezda** [comment]
Aha, i see. Well in that case i must again say thank you for all your help
(Piwik + AD is now in working state).

With best regards!

2015-04-15 2:04 GMT+02:00 Benaka <notifications@github.com>:
