### ISSUE TITLE
ldap password stored in cleartext

### ISSUE THREAD

**Issue by phrend** [piwik/plugin-LoginLdap#97]
I'm not crazy about the fact that the ldap password is stored in config.ini.php in cleartext. Is there any way to:
1. store the password as a hash?
2. include the password from an external file?

Thanks!

**Comment by diosmosis** [comment]
The password has to be sent to the LDAP connection, so it can't be a hash (we can't go back to the password from the hash). Encrypting and/or loading from another source is a possibility, but it's not currently supported, and likely won't be in the near future.

**Comment by phrend** [comment]
@diosmosis gotcha - thanks for the speedy reply!

Just some background:
Our policy is to source all secrets from /foo/bar/secret-dir/*, so allowing the password to be sourced externally would be useful, though I don't know how many other people would be interested in this feature?

**Comment by diosmosis** [comment]
Well, I don't think it's currently a high priority for Piwik, and if it were to be done eventually, it could be a while, but if you'd like to sponsor some custom development, you could contact Piwik PRO at sales@piwik.pro or via: http://piwik.pro/contact.

CC @mattab

**Comment by mattab** [comment]
the LDAP password has to be stored in the config file for now...

However we will: Do not display the LDAP password in the Plugin settings #119
